apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-world-vs
spec:
  gateways:
  - ingress-gateway
  hosts:
  - "*"
  http:
  - name: "hello-world"
    route:
    - destination:
        host: hello-world-svc.default.svc.cluster.local
